"""Building the evidence registry for one investigation.

The registry is the contract with the model: it sees these items, cites them by id, and
application code rejects any id that is not here. Ids are minted from the source record
so they are stable and meaningful (`deployment:DEP-2041`), never generated by the model.

Evidence summaries are written by this module from typed records. Free text that
originated with a *user* — a ticket description — is included, but it is fenced and
labelled as untrusted where the prompt is assembled, not here.
"""

from collections.abc import Sequence
from datetime import datetime

from app.correlation.models import CandidateIncident, CorrelationTicket
from app.investigation.models import EvidenceItem, EvidenceKind
from app.investigation.tools import (
    SYNTHETIC_PROVENANCE,
    DeploymentRecord,
    ErrorSummary,
    ServiceHealthSnapshot,
)
from app.retrieval.models import RetrievalHit

CORRELATION_PROVENANCE = "IncidentIQ deterministic correlation"
TICKET_PROVENANCE = "Reported ticket (user-provided text)"
TEMPORAL_PROVENANCE = "IncidentIQ deterministic temporal analysis"


class EvidenceRegistry:
    """The evidence supplied to one investigation, addressable by id."""

    def __init__(self, items: Sequence[EvidenceItem]) -> None:
        self._items: dict[str, EvidenceItem] = {}
        for item in items:
            if item.id in self._items:
                raise ValueError(f"duplicate evidence id: {item.id}")
            self._items[item.id] = item

    def __len__(self) -> int:
        return len(self._items)

    def __contains__(self, evidence_id: object) -> bool:
        return evidence_id in self._items

    @property
    def ids(self) -> tuple[str, ...]:
        return tuple(self._items)

    @property
    def items(self) -> tuple[EvidenceItem, ...]:
        return tuple(self._items.values())

    def get(self, evidence_id: str) -> EvidenceItem | None:
        return self._items.get(evidence_id)

    def unknown(self, evidence_ids: Sequence[str]) -> tuple[str, ...]:
        """Ids the model cited that this investigation never supplied."""
        return tuple(
            sorted({value for value in evidence_ids if value not in self._items})
        )


def build_registry(
    *,
    candidate: CandidateIncident,
    tickets: Sequence[CorrelationTicket],
    deployments: Sequence[DeploymentRecord],
    health: Sequence[ServiceHealthSnapshot],
    errors: Sequence[ErrorSummary],
    historical: Sequence[RetrievalHit],
) -> EvidenceRegistry:
    """Assembles every piece of evidence the investigator is allowed to use."""
    items: list[EvidenceItem] = []

    by_id = {ticket.id: ticket for ticket in tickets}
    for ticket_id in candidate.ticket_ids:
        ticket = by_id.get(ticket_id)
        if ticket is None:
            continue
        items.append(
            EvidenceItem(
                id=f"ticket:{ticket.id}",
                kind=EvidenceKind.TICKET,
                summary=f"{ticket.title}. {ticket.description}".strip(". "),
                source_id=ticket.id,
                provenance=TICKET_PROVENANCE,
                observed_at=ticket.created_at,
                service_id=ticket.service_id,
                attributes={"ticket_id": ticket.id},
            )
        )

    items.append(
        EvidenceItem(
            id=f"correlation:{candidate.id}",
            kind=EvidenceKind.CORRELATION,
            summary=_correlation_summary(candidate),
            source_id=candidate.id,
            provenance=CORRELATION_PROVENANCE,
            observed_at=candidate.first_seen,
            service_id=candidate.service_id,
        )
    )

    for deployment in deployments:
        gap = _minutes_between(deployment.deployed_at, candidate.first_seen)
        items.append(
            EvidenceItem(
                id=f"deployment:{deployment.id}",
                kind=EvidenceKind.DEPLOYMENT,
                summary=(
                    f"{deployment.service_id} version {deployment.version} deployed "
                    f"{gap} the first report, status {deployment.status}. "
                    f"{deployment.change_summary}"
                ),
                source_id=deployment.id,
                provenance=SYNTHETIC_PROVENANCE,
                observed_at=deployment.deployed_at,
                service_id=deployment.service_id,
                attributes={
                    "deployment_id": deployment.id,
                    "version": deployment.version,
                    "status": deployment.status,
                },
            )
        )

    # Every health observation in the window, not just the closest one. The sequence is
    # what makes "healthy at 08:40, degraded at 09:10" visible as a change rather than as
    # a state.
    for snapshot in health:
        items.append(
            EvidenceItem(
                id=f"health:{snapshot.service_id}@{snapshot.observed_at.isoformat()}",
                kind=EvidenceKind.HEALTH,
                summary=(
                    f"{snapshot.service_id} health {snapshot.status} at "
                    f"{snapshot.observed_at.isoformat()}: {'; '.join(snapshot.signals)}"
                ),
                source_id=snapshot.service_id,
                provenance=SYNTHETIC_PROVENANCE,
                observed_at=snapshot.observed_at,
                service_id=snapshot.service_id,
                attributes={"status": snapshot.status},
            )
        )

    for error in errors:
        items.append(
            EvidenceItem(
                id=f"error:{error.code}",
                kind=EvidenceKind.ERROR,
                summary=(
                    f"{error.code} on {error.service_id}: {error.count} occurrences "
                    f"between {error.first_seen.isoformat()} and "
                    f"{error.last_seen.isoformat()}. {error.sample_message}"
                ),
                source_id=error.code,
                provenance=SYNTHETIC_PROVENANCE,
                observed_at=error.first_seen,
                service_id=error.service_id,
                attributes={
                    "error_code": error.code,
                    "count": str(error.count),
                    "last_seen": error.last_seen.isoformat(),
                },
            )
        )

    for hit in historical:
        items.append(
            EvidenceItem(
                id=f"historical:{hit.incident.id}",
                kind=EvidenceKind.HISTORICAL,
                summary=(
                    f"Past incident (similarity {hit.score:.2f}): {hit.incident.title}. "
                    f"Symptoms then: {hit.incident.summary} "
                    f"Root cause of THAT incident: {hit.incident.outcome.root_cause}"
                ),
                source_id=hit.incident.id,
                provenance=f"{hit.incident.provenance.value} historical record",
                observed_at=hit.incident.occurred_at,
            )
        )

    # --- derived temporal evidence ---------------------------------------------------
    #
    # Added last, over the observations just assembled, so every temporal fact points at
    # evidence the model can also read directly. These carry system-minted ids like any
    # other evidence: the model may cite them, and citing one that was not supplied fails
    # validation exactly as an invented deployment id would.
    items.extend(temporal_evidence(incident_id=candidate.id, evidence=items))

    return EvidenceRegistry(items)


def temporal_evidence(
    *, incident_id: str, evidence: Sequence[EvidenceItem]
) -> list[EvidenceItem]:
    """Chronology, as citable evidence items.

    Deliberately a small set. Every pair of observations could be compared; only the
    comparisons that bear on "could this deployment have started it" and "did we see it
    before the customers did" are derived, so the registry gains a handful of items rather
    than a quadratic pile.
    """
    from app.temporal import build_timeline

    timeline = build_timeline(incident_id=incident_id, evidence=evidence)
    derived: list[EvidenceItem] = []

    if timeline.onset_at is not None:
        derived.append(
            EvidenceItem(
                id=f"temporal:onset:{incident_id}",
                kind=EvidenceKind.TEMPORAL,
                summary=(
                    f"Incident symptom onset {timeline.onset_at.isoformat()}. "
                    f"{timeline.onset_basis}."
                ),
                source_id=incident_id,
                provenance=TEMPORAL_PROVENANCE,
                observed_at=timeline.onset_at,
                attributes={
                    "onset_evidence_id": timeline.onset_evidence_id or "",
                    "config_version": timeline.config_version,
                },
            )
        )

    for relationship in timeline.relationships:
        derived.append(
            EvidenceItem(
                id=relationship.id,
                kind=EvidenceKind.TEMPORAL,
                summary=f"{relationship.detail}.",
                source_id=relationship.relationship_type.value,
                provenance=TEMPORAL_PROVENANCE,
                attributes={
                    "delta_seconds": str(relationship.delta_seconds),
                    "compatibility": relationship.compatibility.value,
                    "subject": relationship.subject_evidence_id,
                    "object": relationship.object_evidence_id,
                },
            )
        )

    for attribution in timeline.attributions:
        derived.append(
            EvidenceItem(
                id=f"temporal:attribution:{attribution.deployment_id}",
                kind=EvidenceKind.TEMPORAL,
                summary=(
                    f"Deployment {attribution.deployment_id} on {attribution.service_id}: "
                    f"{attribution.detail}."
                ),
                source_id=attribution.deployment_id,
                provenance=TEMPORAL_PROVENANCE,
                attributes={
                    "temporally_plausible": str(attribution.temporally_plausible).lower(),
                    "seconds_before_onset": str(attribution.seconds_before_onset),
                    "compatibility": attribution.compatibility.value,
                },
            )
        )

    return derived


def _correlation_summary(candidate: CandidateIncident) -> str:
    supporting = "; ".join(signal.detail for signal in candidate.supporting_signals)
    conflicting = "; ".join(signal.detail for signal in candidate.conflicting_signals)
    parts = [
        f"{candidate.ticket_count} tickets grouped with score {candidate.score} "
        f"({candidate.confidence.value} confidence)."
    ]
    if supporting:
        parts.append(f"Supporting: {supporting}.")
    if conflicting:
        parts.append(f"Conflicting: {conflicting}.")
    return " ".join(parts)


def _minutes_between(earlier: datetime, later: datetime) -> str:
    minutes = (later - earlier).total_seconds() / 60
    if minutes < 0:
        return f"{abs(minutes):.0f} minutes after"
    if minutes < 90:
        return f"{minutes:.0f} minutes before"
    return f"{minutes / 60:.1f} hours before"
