"""Building the evidence registry for one investigation.

The registry is the contract with the model: it sees these items, cites them by id, and
application code rejects any id that is not here. Ids are minted from the source record
so they are stable and meaningful (`deployment:DEP-2041`), never generated by the model.

Evidence summaries are written by this module from typed records. Free text that
originated with a *user* — a ticket description — is included, but it is fenced and
labelled as untrusted where the prompt is assembled, not here.
"""

from collections.abc import Sequence
from datetime import datetime

from app.correlation.models import CandidateIncident, CorrelationTicket
from app.investigation.models import EvidenceItem, EvidenceKind
from app.investigation.tools import (
    SYNTHETIC_PROVENANCE,
    DeploymentRecord,
    ErrorSummary,
    ServiceHealthSnapshot,
)
from app.retrieval.models import RetrievalHit

CORRELATION_PROVENANCE = "IncidentIQ deterministic correlation"
TICKET_PROVENANCE = "Reported ticket (user-provided text)"


class EvidenceRegistry:
    """The evidence supplied to one investigation, addressable by id."""

    def __init__(self, items: Sequence[EvidenceItem]) -> None:
        self._items: dict[str, EvidenceItem] = {}
        for item in items:
            if item.id in self._items:
                raise ValueError(f"duplicate evidence id: {item.id}")
            self._items[item.id] = item

    def __len__(self) -> int:
        return len(self._items)

    def __contains__(self, evidence_id: object) -> bool:
        return evidence_id in self._items

    @property
    def ids(self) -> tuple[str, ...]:
        return tuple(self._items)

    @property
    def items(self) -> tuple[EvidenceItem, ...]:
        return tuple(self._items.values())

    def get(self, evidence_id: str) -> EvidenceItem | None:
        return self._items.get(evidence_id)

    def unknown(self, evidence_ids: Sequence[str]) -> tuple[str, ...]:
        """Ids the model cited that this investigation never supplied."""
        return tuple(
            sorted({value for value in evidence_ids if value not in self._items})
        )


def build_registry(
    *,
    candidate: CandidateIncident,
    tickets: Sequence[CorrelationTicket],
    deployments: Sequence[DeploymentRecord],
    health: ServiceHealthSnapshot | None,
    errors: Sequence[ErrorSummary],
    historical: Sequence[RetrievalHit],
) -> EvidenceRegistry:
    """Assembles every piece of evidence the investigator is allowed to use."""
    items: list[EvidenceItem] = []

    by_id = {ticket.id: ticket for ticket in tickets}
    for ticket_id in candidate.ticket_ids:
        ticket = by_id.get(ticket_id)
        if ticket is None:
            continue
        items.append(
            EvidenceItem(
                id=f"ticket:{ticket.id}",
                kind=EvidenceKind.TICKET,
                summary=f"{ticket.title}. {ticket.description}".strip(". "),
                source_id=ticket.id,
                provenance=TICKET_PROVENANCE,
                observed_at=ticket.created_at,
            )
        )

    items.append(
        EvidenceItem(
            id=f"correlation:{candidate.id}",
            kind=EvidenceKind.CORRELATION,
            summary=_correlation_summary(candidate),
            source_id=candidate.id,
            provenance=CORRELATION_PROVENANCE,
            observed_at=candidate.first_seen,
        )
    )

    for deployment in deployments:
        gap = _minutes_between(deployment.deployed_at, candidate.first_seen)
        items.append(
            EvidenceItem(
                id=f"deployment:{deployment.id}",
                kind=EvidenceKind.DEPLOYMENT,
                summary=(
                    f"{deployment.service_id} version {deployment.version} deployed "
                    f"{gap} the first report, status {deployment.status}. "
                    f"{deployment.change_summary}"
                ),
                source_id=deployment.id,
                provenance=SYNTHETIC_PROVENANCE,
                observed_at=deployment.deployed_at,
            )
        )

    if health is not None:
        items.append(
            EvidenceItem(
                id=f"health:{health.service_id}@{health.observed_at.isoformat()}",
                kind=EvidenceKind.HEALTH,
                summary=(
                    f"{health.service_id} health {health.status} at "
                    f"{health.observed_at.isoformat()}: {'; '.join(health.signals)}"
                ),
                source_id=health.service_id,
                provenance=SYNTHETIC_PROVENANCE,
                observed_at=health.observed_at,
            )
        )

    for error in errors:
        items.append(
            EvidenceItem(
                id=f"error:{error.code}",
                kind=EvidenceKind.ERROR,
                summary=(
                    f"{error.code} on {error.service_id}: {error.count} occurrences "
                    f"between {error.first_seen.isoformat()} and "
                    f"{error.last_seen.isoformat()}. {error.sample_message}"
                ),
                source_id=error.code,
                provenance=SYNTHETIC_PROVENANCE,
                observed_at=error.first_seen,
            )
        )

    for hit in historical:
        items.append(
            EvidenceItem(
                id=f"historical:{hit.incident.id}",
                kind=EvidenceKind.HISTORICAL,
                summary=(
                    f"Past incident (similarity {hit.score:.2f}): {hit.incident.title}. "
                    f"Symptoms then: {hit.incident.summary} "
                    f"Root cause of THAT incident: {hit.incident.outcome.root_cause}"
                ),
                source_id=hit.incident.id,
                provenance=f"{hit.incident.provenance.value} historical record",
                observed_at=hit.incident.occurred_at,
            )
        )

    return EvidenceRegistry(items)


def _correlation_summary(candidate: CandidateIncident) -> str:
    supporting = "; ".join(signal.detail for signal in candidate.supporting_signals)
    conflicting = "; ".join(signal.detail for signal in candidate.conflicting_signals)
    parts = [
        f"{candidate.ticket_count} tickets grouped with score {candidate.score} "
        f"({candidate.confidence.value} confidence)."
    ]
    if supporting:
        parts.append(f"Supporting: {supporting}.")
    if conflicting:
        parts.append(f"Conflicting: {conflicting}.")
    return " ".join(parts)


def _minutes_between(earlier: datetime, later: datetime) -> str:
    minutes = (later - earlier).total_seconds() / 60
    if minutes < 0:
        return f"{abs(minutes):.0f} minutes after"
    if minutes < 90:
        return f"{minutes:.0f} minutes before"
    return f"{minutes / 60:.1f} hours before"
