"""audit sequence as an identity column

Revision ID: 542c908d7e8f
Revises: 2d1e67318f0a
Create Date: 2026-08-29 18:21:48.900925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '542c908d7e8f'
down_revision: Union[str, Sequence[str], None] = '2d1e67318f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Make audit_events.sequence generate itself.

    It was declared with `autoincrement=True`, which does nothing on a column that is not
    the primary key: SQLAlchemy filled it with NULL and every insert failed the NOT NULL
    check. Audit ordering depends on this column, so it has to be generated by the
    database rather than by whichever process happens to be writing.
    """
    op.execute("ALTER TABLE audit_events ALTER COLUMN sequence TYPE bigint")
    op.execute(
        "ALTER TABLE audit_events ALTER COLUMN sequence "
        "ADD GENERATED BY DEFAULT AS IDENTITY"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("ALTER TABLE audit_events ALTER COLUMN sequence DROP IDENTITY IF EXISTS")
    op.execute("ALTER TABLE audit_events ALTER COLUMN sequence TYPE integer")
