"""runtime ticket intake and candidate persistence

Revision ID: cdcf60677681
Revises: 7f4d18c40529
Create Date: 2026-08-30 03:35:29.253625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdcf60677681'
down_revision: Union[str, Sequence[str], None] = '7f4d18c40529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_incidents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('correlation_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=True),
    sa.Column('issue_type', sa.String(length=64), nullable=True),
    sa.Column('ticket_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('distinct_reporters', sa.Integer(), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'stale', 'resolved')", name='ck_candidates_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_incidents_service_id'), 'candidate_incidents', ['service_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reported_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reported_service_id', sa.String(length=64), nullable=True),
    sa.Column('service_id', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('issue_type', sa.String(length=64), nullable=True),
    sa.Column('triage_version', sa.String(length=64), nullable=True),
    sa.Column('triage_signals', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('candidate_id', sa.String(length=64), nullable=True),
    sa.CheckConstraint("source IN ('api', 'northstar-authored', 'imported', 'external-eval')", name='ck_tickets_source'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_tickets_candidate_id'), 'tickets', ['candidate_id'], unique=False)
    op.create_index('ix_tickets_created', 'tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_tickets_service_id'), 'tickets', ['service_id'], unique=False)
    op.create_index(op.f('ix_tickets_source'), 'tickets', ['source'], unique=False)
    op.create_table('correlation_decisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ticket_id', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('correlation_version', sa.String(length=64), nullable=False),
    sa.Column('triage_version', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('created_new_candidate', sa.Boolean(), nullable=False),
    sa.Column('supporting_signals', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('conflicting_signals', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("outcome IN ('attached', 'created_candidate', 'uncorrelated', 'ambiguous', 'failed')", name='ck_correlation_decisions_outcome'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correlation_decisions_candidate_id'), 'correlation_decisions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_correlation_decisions_ticket_id'), 'correlation_decisions', ['ticket_id'], unique=False)
    op.drop_index(op.f('uq_investigation_runs_one_active'), table_name='investigation_runs', postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, 'running'::character varying])::text[]))")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_investigation_runs_one_active'), 'investigation_runs', ['incident_id'], unique=True, postgresql_where="((status)::text = ANY ((ARRAY['pending'::character varying, 'running'::character varying])::text[]))")
    op.drop_index(op.f('ix_correlation_decisions_ticket_id'), table_name='correlation_decisions')
    op.drop_index(op.f('ix_correlation_decisions_candidate_id'), table_name='correlation_decisions')
    op.drop_table('correlation_decisions')
    op.drop_index(op.f('ix_tickets_source'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_service_id'), table_name='tickets')
    op.drop_index('ix_tickets_created', table_name='tickets')
    op.drop_index(op.f('ix_tickets_candidate_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_candidate_incidents_service_id'), table_name='candidate_incidents')
    op.drop_table('candidate_incidents')
    # ### end Alembic commands ###
