"""durable workflow state and historical corpus

Revision ID: d45627f8a057
Revises: 
Create Date: 2026-08-29 18:11:16.030235

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd45627f8a057'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector first: historical_incidents.embedding is a vector column and cannot be
    # created without it. IF NOT EXISTS so the migration is safe on a database where an
    # operator already enabled the extension by hand.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_incidents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=128), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('services', postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('observed_errors', postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('resolution_steps', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('indexed_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('embedding_provider', sa.String(length=64), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('service_tokens', postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('error_tokens', postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provenance', 'source_record_id', name='uq_historical_source')
    )
    op.create_index(op.f('ix_historical_incidents_provenance'), 'historical_incidents', ['provenance'], unique=False)
    op.create_table('investigation_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=128), nullable=False),
    sa.Column('investigator_version', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_snapshot', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('structured_result', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=True),
    sa.Column('failure_type', sa.String(length=64), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed')", name='ck_investigation_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_investigation_runs_incident_created', 'investigation_runs', ['incident_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_investigation_runs_incident_id'), 'investigation_runs', ['incident_id'], unique=False)
    op.create_index(op.f('ix_investigation_runs_status'), 'investigation_runs', ['status'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=128), nullable=False),
    sa.Column('investigation_run_id', sa.String(length=64), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('target', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('model_stated_risk', sa.String(length=16), nullable=True),
    sa.Column('effective_risk', sa.String(length=16), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('policy_decision', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('recommendation_summary', sa.Text(), nullable=False),
    sa.Column('recommendation_evidence_ids', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('validated_evidence_ids', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_run_id'], ['investigation_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_incident_id'), 'actions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_actions_investigation_run_id'), 'actions', ['investigation_run_id'], unique=False)
    op.create_index(op.f('ix_actions_status'), 'actions', ['status'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('action_id', sa.String(length=64), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.CheckConstraint("actor_type = 'human'", name='ck_approvals_actor_is_human'),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id', name='uq_approvals_action')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=128), nullable=False),
    sa.Column('action_id', sa.String(length=64), nullable=True),
    sa.Column('investigation_run_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.CheckConstraint("NOT (actor_type = 'model' AND event_type LIKE 'execution%%')", name='ck_audit_events_model_never_executes'),
    sa.CheckConstraint("actor_type IN ('model', 'system', 'human')", name='ck_audit_events_actor_type'),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_run_id'], ['investigation_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence')
    )
    op.create_index(op.f('ix_audit_events_action_id'), 'audit_events', ['action_id'], unique=False)
    op.create_index(op.f('ix_audit_events_incident_id'), 'audit_events', ['incident_id'], unique=False)
    op.create_index(op.f('ix_audit_events_investigation_run_id'), 'audit_events', ['investigation_run_id'], unique=False)
    op.create_index('ix_audit_events_order', 'audit_events', ['occurred_at', 'sequence'], unique=False)
    op.create_table('execution_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('action_id', sa.String(length=64), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('simulated', name='ck_execution_results_simulated_only'),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id', name='uq_execution_results_action')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    The extension is deliberately not dropped. It is database-wide and something else
    may be using it; a schema downgrade should not reach outside its own tables.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('execution_results')
    op.drop_index('ix_audit_events_order', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_investigation_run_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_incident_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_actions_status'), table_name='actions')
    op.drop_index(op.f('ix_actions_investigation_run_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_incident_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_investigation_runs_status'), table_name='investigation_runs')
    op.drop_index(op.f('ix_investigation_runs_incident_id'), table_name='investigation_runs')
    op.drop_index('ix_investigation_runs_incident_created', table_name='investigation_runs')
    op.drop_table('investigation_runs')
    op.drop_index(op.f('ix_historical_incidents_provenance'), table_name='historical_incidents')
    op.drop_table('historical_incidents')
    # ### end Alembic commands ###
